[package]
name = "ruc-evm-precompile-simple"
version = "2.0.0"
edition = "2021"
description = "..."
license = "Apache-2.0"
<<<<<<< HEAD
description = "Simple precompiles for EVM pallet."
repository = "https://github.com/paritytech/frontier/"

[dependencies]
ripemd = { version = "0.1", default-features = false }

# Substrate
sp-io = { version = "6.0.0", git = "https://github.com/paritytech/substrate", branch = "master", default-features = false }

# Frontier
fp-evm = { version = "3.0.0-dev", path = "../../../../primitives/evm", default-features = false }

[dev-dependencies]
pallet-evm-test-vector-support = { version = "1.0.0-dev", path = "../../test-vector-support" }

[features]
default = ["std"]
std = [
	"ripemd/std",
	# Substrate
	"sp-io/std",
	# Frontier
	"fp-evm/std",
]
=======
homepage = "https://github.com/rust-util-collections/frontier"
repository = "https://github.com/rust-util-collections/frontier"

[dependencies]
ripemd = { version = "0.1", default-features = false }
sp-io = "6.0.0"
fp-evm = { package = "ruc-fp-evm", path = "../../../../primitives/evm" }

[dev-dependencies]
ruc-evm-test-vector-support = { version = "1.0.0", path = "../../test-vector-support" }
>>>>>>> 10df058 (rm needless compenents)
