[package]
name = "pallet-evm-precompile-sha3fips"
version = "2.0.0-dev"
edition = "2021"

[dependencies]
tiny-keccak = { version = "2.0", features = ["fips202"] }
fp-evm = { version = "3.0.0-dev", path = "../../../../primitives/evm" }
