[package]
name = "pallet-evm-precompile-blake2"
version = "2.0.0-dev"
edition = "2021"

[dependencies]
fp-evm = { version = "3.0.0-dev", path = "../../../../primitives/evm" }

[dev-dependencies]
pallet-evm-test-vector-support = { version = "1.0.0-dev", path = "../../test-vector-support" }
