[package]
name = "ruc-evm-precompile-blake2"
version = "2.0.0"
edition = "2021"
description = "..."
license = "Apache-2.0"
<<<<<<< HEAD
description = "BLAKE2 precompiles for EVM pallet."
repository = "https://github.com/paritytech/frontier/"

[dependencies]
# Frontier
fp-evm = { version = "3.0.0-dev", path = "../../../../primitives/evm", default-features = false }

[dev-dependencies]
pallet-evm-test-vector-support = { version = "1.0.0-dev", path = "../../test-vector-support" }

[features]
default = ["std"]
std = [
	# Frontier
	"fp-evm/std",
]
=======
homepage = "https://github.com/rust-util-collections/frontier"
repository = "https://github.com/rust-util-collections/frontier"

[dependencies]
fp-evm = { package = "ruc-fp-evm", path = "../../../../primitives/evm" }

[dev-dependencies]
ruc-evm-test-vector-support = { version = "1.0.0", path = "../../test-vector-support" }
>>>>>>> 10df058 (rm needless compenents)
