[package]
name = "pallet-evm-precompile-curve25519"
version = "1.0.0-dev"
edition = "2021"

[dependencies]
curve25519-dalek = { version = "4.0.0-pre.1", default-features = false, features = ["u64_backend", "alloc"] }
fp-evm = { version = "3.0.0-dev", path = "../../../../primitives/evm" }
