[package]
<<<<<<< HEAD
name = "fp-evm"
version = "3.0.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
description = "Primitive EVM abstractions for Substrate."
repository = "https://github.com/paritytech/frontier/"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
evm = { version = "0.37.0", default-features = false, features = ["with-codec"] }
serde = { version = "1.0", features = ["derive"], optional = true }

# Parity
codec = { package = "parity-scale-codec", version = "3.2.1", default-features = false }

# Substrate
sp-core = { version = "6.0.0", git = "https://github.com/paritytech/substrate", branch = "master", default-features = false }
sp-std = { version = "4.0.0", git = "https://github.com/paritytech/substrate", branch = "master", default-features = false }
# Substrate FRAME
frame-support = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", branch = "master", default-features = false }

[features]
default = ["std"]
std = [
	"evm/std",
	"evm/with-serde",
	"serde",
	# Parity
	"codec/std",
	# Substrate
	"sp-core/std",
	"sp-std/std",
	# Substrate FRAME
	"frame-support/std",
]
=======
name = "ruc-fp-evm"
version = "3.0.0"
license = "Apache-2.0"
edition = "2021"
description = "..."
homepage = "https://github.com/rust-util-collections/frontier"
repository = "https://github.com/rust-util-collections/frontier"

[dependencies]
evm = { version = "0.35.0", default-features = false, features = ["std", "with-serde"] }
>>>>>>> 10df058 (rm needless compenents)
