[package]
name = "pallet-evm-precompile-ed25519"
version = "2.0.0-dev"
edition = "2021"

[dependencies]
ed25519-dalek = { version = "1.0.0", default-features = false, features = ["alloc", "u64_backend"] }
fp-evm = { version = "3.0.0-dev", path = "../../../../primitives/evm" }
